name: Deploy Slack Logger

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
        default: dev

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy_dev:
    if: ${{ inputs.environment == 'dev' }}
    steps:
    - uses: actions/checkout@v4

    - uses: google-github-actions/auth@v2
      id: auth
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ vars.SERVICE_ACCOUNT }}
        export_environment_variables: true
        create_credentials_file: true
      
    - name: Deploy Slack Logger
      run: |
          gcloud functions deploy ieos-platform-dev-logs-handler \
            --gen2 \
            --runtime=go121 \
            --entry-point=SendMessage \
            --trigger-topic="ieos-platform-dev-logs" \
            --source=./ieos-slack-logger \
            --service-account="ieos-platform-dev-logs-fn@ieos-platform-dev.iam.gserviceaccount.com" \
            --memory=256Mi \
            --timeout=60s \
            --ingress-settings=internal-only 
